version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
    ports:
      - 8000:8000
    depends_on:
      - redis
    working_dir: /var/www/
    container_name: larachat-app

  nginx:
    container_name: larachat-nginx
    image: nginx:alpine
    restart: unless-stopped
    ports: 
        - "8989:80"
    volumes: 
        - ./:/var/www
        - ./docker/nginx/:/etc/nginx/conf.d/

  mysql:
    container_name: larachat-mysql
    image: mysql:5.7.22
    restart: unless-stopped
    environment: 
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        MYSQL_PASSWORD: ${DB_PASSWORD}
        MYSQL_USER: ${DB_USERNAME}
    volumes: 
        - ./.docker/mysql/dbdata:/var/lib/mysql
    ports: 
        - "3306:3306"

  redis:
    container_name: larachat-redis
    image: redis:latest